'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 By starting with 1 and 2, the first 10 terms will be:
    1,2,3,5,8,13,21,34,55,89,...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
n1,n2 = 0,1
arr = []
max  = 4000000
while n1 <= max:
    next_val = n1 + n2
    n1 = n2
    n2 = next_val
    if n1 % 2 == 0:
        arr.append(n1)

result = sum(arr)
print(result)



